name: Daily Random Programming Quote

on:
  schedule:
    - cron: "*/5 * * * *"   # Every 5 minutes PH Time adjusted by UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run script
        run: node scripts/update_readme.js

      - name: Commit & Push
        run: |
          git config --local user.email "paleraciojoey68@gmail.com"
          git config --local user.name "dvshaoo"
          git add -A
          git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M:%S')" --allow-empty
          git push
